

using Content.Client.UserInterface.Controls;
using Content.Shared._Erida.DirectionalEmote;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Erida.DirectionalEmote;

[GenerateTypedNameReferences]
public sealed partial class DirectionalEmoteWindow : FancyWindow
{
    public NetEntity Source;
    public NetEntity Target;
    public string Text = "";
    public Action? AcceptPressed;
    public Action? MessageChanged;
    public DirectionalEmoteWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ => AcceptPressed?.Invoke();
        MessageInput.OnTextChanged += e =>
        {
            Text = Rope.Collapse(e.TextRope).Trim();
            MessageChanged?.Invoke();
        };
        CloseButton.OnPressed += _ => Dispose();
    }
}
