using System.Numerics;
using Content.Shared._Erida.Circuits.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.ViewVariables;
using Robust.Shared.Input;

namespace Content.Client._Erida.Circuits.Setup;

[GenerateTypedNameReferences]
public sealed partial class CircuitNodeControl : PanelContainer
{
    private static readonly Color BgColor = Color.FromHex("#0e0c16");
    private static readonly Color BorderColor = Color.FromHex("#1c1826");
    private static readonly Color TitleColor = Color.FromHex("#a898bc");
    private static readonly Color LineColor = Color.FromHex("#4a3d5c");
    private static readonly Color CircleColor = Color.FromHex("#8a6fac");

    public readonly EntityUid Entity;

    public readonly List<CircuitPortControl> InputPorts = [];
    public readonly List<CircuitPortControl> OutputPorts = [];

    private bool _dragging;
    private Entity<CircuitComponentComponent> _componentComponent;

    public event Action<EntityUid>? OnDeleteRequested;

    public CircuitNodeControl(Entity<CircuitComponentComponent> ent, CircuitSetupCanvasControl canvasControl)
    {
        RobustXamlLoader.Load(this);
        Entity = ent.Owner;

        MouseFilter = MouseFilterMode.Stop;

        DebugButton.Visible = false;

#if DEBUG
        DebugButton.Visible = true;
        var vv = IoCManager.Resolve<IClientViewVariablesManager>();
        DebugButton.OnPressed += (args) =>
        {
            vv.OpenVV(_componentComponent.Owner);
        };
#endif

        _componentComponent = ent;

        LayoutContainer.SetPosition(this, _componentComponent.Comp.PositionInSetup);

        DeleteButton.ToolTip = Loc.GetString("circuit-setup-interface-button-tooltip-delete");

        TitleLabel.Text = Loc.GetString($"circuit-setup-interface-component-{ent.Comp.AnswerType}");
        TitleLabel.FontColorOverride = TitleColor;

        RootPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = BgColor,
            BorderColor = BorderColor,
            BorderThickness = new Thickness(1),
        };

        DeleteButton.OnPressed += _ => OnDeleteRequested?.Invoke(ent.Owner);

        Rebuild(ent.Comp);
    }

    public void Rebuild(CircuitComponentComponent comp)
    {
        InputsBox.RemoveAllChildren();
        OutputsBox.RemoveAllChildren();
        InputPorts.Clear();
        OutputPorts.Clear();

        for (var i = 0; i < comp.Inputs.Length; i++)
        {
            var port = new CircuitPortControl(Entity, i, PortDirection.Input, comp.Inputs[i]);
            InputPorts.Add(port);
            InputsBox.AddChild(port);
        }

        for (var i = 0; i < comp.Output.Length; i++)
        {
            var port = new CircuitPortControl(Entity, i, PortDirection.Output, comp.Output[i]);
            OutputPorts.Add(port);
            OutputsBox.AddChild(port);
        }
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var size = PixelSize;
        if (size.X <= 0 || size.Y <= 0)
            return;

        DrawUnderline(handle, size);
    }

    private void DrawUnderline(DrawingHandleScreen handle, Vector2 size)
    {
        var localY = AccentDivider.GlobalPixelPosition.Y - GlobalPixelPosition.Y + AccentDivider.PixelSize.Y / 2f;

        var spaceBetweenDotAndLine = 4f;

        var xStart = 10f;
        var xEnd = size.X - 10f;

        var radius = 2f;

        handle.DrawCircle(new Vector2(xStart, localY), radius, color: CircleColor, filled: true);
        handle.DrawCircle(new Vector2(xEnd, localY), radius, CircleColor, filled: true);
        handle.DrawLine(new Vector2(xStart + spaceBetweenDotAndLine, localY), new Vector2(xEnd - spaceBetweenDotAndLine, localY), LineColor);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragging = true;
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragging = false;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_dragging)
            return;

        var newPos = args.SourceControl.Position + args.Relative;

        LayoutContainer.SetPosition(this, newPos);
        _componentComponent.Comp.PositionInSetup = newPos;
    }
}
