using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Erida.Circuits.Setup;

[GenerateTypedNameReferences]
public sealed partial class CircuitHudPanel : PanelContainer
{
    private const float CutWidth = 40f;

    private static readonly Color BgColor = Color.FromHex("#0e0c16").WithAlpha(0.92f);
    private static readonly Color BorderColor = Color.FromHex("#3a2f4a");
    private static readonly Color ActiveColor = Color.FromHex("#8fdc9a");
    private static readonly Color InactiveColor = Color.FromHex("#6a5f78");
    private static readonly Color PercentColor = Color.FromHex("#a898bc");

    public event Action? OnCloseRequested;

    private bool _active;
    private float _percent;

    public CircuitHudPanel()
    {
        RobustXamlLoader.Load(this);

        HudCloseButton.OnPressed += _ => OnCloseRequested?.Invoke();
        PercentLabel.FontColorOverride = PercentColor;

        Refresh();
    }

    public void SetActive(bool active)
    {
        _active = active;
        Refresh();
    }

    public void SetPercent(float percent)
    {
        _percent = Math.Clamp(percent, 0f, 100f);
        Refresh();
    }

    private void Refresh()
    {
        StatusLabel.Text = _active ? "Active" : "Inactive";
        StatusLabel.FontColorOverride = _active ? ActiveColor : InactiveColor;
        PercentLabel.Text = $"{_percent:0}%";
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        var size = PixelSize;
        if (size.X <= 0 || size.Y <= 0)
            return;

        var points = new[]
        {
            new Vector2(0, 0),
            new Vector2(size.X, 0),
            new Vector2(size.X, size.Y),
            new Vector2(CutWidth, size.Y),
        };

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, points, BgColor);

        for (var i = 0; i < points.Length; i++)
        {
            var a = points[i];
            var b = points[(i + 1) % points.Length];
            handle.DrawLine(a, b, BorderColor);
        }

        base.Draw(handle);
    }
}
