using Content.Shared._Erida.Circuits;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.IoC;

namespace Content.Client._Erida.Circuits.Setup;

public enum PortDirection : byte { Input, Output }

[GenerateTypedNameReferences]
public sealed partial class CircuitPortControl : PanelContainer
{
    [Dependency] private IUserInterfaceManager _uiManager = default!;

    public readonly EntityUid Owner;
    public readonly int Index;
    public readonly PortDirection Direction;
    public CircuitPortData Data;

    private readonly CircuitPortMarker _marker = new();
    private readonly Label _label = new() { StyleClasses = { "LabelSmall" } };

    public CircuitPortControl(EntityUid owner, int index, PortDirection direction, CircuitPortData data)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MouseFilter = MouseFilterMode.Stop;

        Owner = owner;
        Index = index;
        Direction = direction;
        Data = data;

        _label.FontColorOverride = Color.FromHex("#6a7078");

        if (direction == PortDirection.Input)
        {
            Row.AddChild(_marker);
            Row.AddChild(_label);
        }
        else
        {
            Row.AddChild(_label);
            Row.AddChild(_marker);
        }

        Refresh();
    }

    public void Refresh()
    {
        _label.Text = $"{Index} · {Data.DataType}";

        _marker.Connected = Data.ConnectedComponent.HasValue && Data.ConnectedIndex.HasValue;
    }

    private CircuitSetupCanvasControl? FindCanvas()
    {
        var current = Parent;
        while (current is not null)
        {
            if (current is CircuitSetupCanvasControl canvas)
                return canvas;
            current = current.Parent;
        }
        return null;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        FindCanvas()?.BeginWireDrag(this);
        args.Handle();
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        var target = _uiManager.CurrentlyHovered as CircuitPortControl;
        FindCanvas()?.EndWireDrag(target);
        args.Handle();
    }
}

public static class CircuitPortColors
{
    public static readonly Dictionary<CircuitDataFormat, Color> Map = new()
    {
        { CircuitDataFormat.Boolean, Color.FromHex("#e0896f") },
        { CircuitDataFormat.Number,  Color.FromHex("#6fc9b8") },
        { CircuitDataFormat.ProtoId, Color.FromHex("#c98fd6") },
        { CircuitDataFormat.String,  Color.FromHex("#e0c66f") },
        { CircuitDataFormat.Signal,  Color.FromHex("#9a7fc0") },
    };



    public static Color GetColor(CircuitDataFormat type) =>
        Map.GetValueOrDefault(type, Color.Gray);
}
