using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Erida.Circuits;
using Content.Shared._Erida.Circuits.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client._Erida.Circuits.Setup;

[GenerateTypedNameReferences]
public sealed partial class CircuitSetupWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private SharedCircuitSystem _sharedCircuit = default!;

    public EntityUid Owner;
    public readonly CircuitSetupCanvasControl CanvasControl;
    public CircuitHudPanel CircuitHud;
    private bool _draggin;

    public event Action<EntityUid, byte, EntityUid, byte>? OnLinkRequested;
    public event Action<EntityUid>? OnDeleteRequested;

    public CircuitSetupWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sharedCircuit = _entityManager.System<SharedCircuitSystem>();

        MouseFilter = MouseFilterMode.Pass;

        Children[1].RemoveChild(Children[1].Children[0]);
        Children[0].Visible = false;

        HudPanel.OnCloseRequested += Close;

        Canvas.OnKeyBindDown += OnKeybindDown;
        Canvas.OnKeyBindUp += OnKeybindUp;

        Canvas.OnLinkRequested += (from, fromIdx, to, toIdx) =>
            OnLinkRequested?.Invoke(from, fromIdx, to, toIdx);

        CanvasControl = Canvas;
        CircuitHud = HudPanel;

        if (_sharedCircuit.GetChargeLevelFromSlot(Owner, out var charge))
            CircuitHud.SetPercent(charge.Value * 100);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.None;
    }

    public void SetEntity(EntityUid owner)
    {
        Owner = owner;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        foreach (var child in Canvas.Children)
            LayoutContainer.SetPosition(child, child.Position + args.Relative);
    }

    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }

    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }

    public void UpdatePanels()
    {
        if (!_entityManager.TryGetComponent<CircuitSetupComponent>(Owner, out var setupComponent)
            || setupComponent.PartsContainer == null)
            return;

        Canvas.ClearNodes();

        foreach (var entity in setupComponent.PartsContainer.ContainedEntities)
            if (_entityManager.TryGetComponent<CircuitComponentComponent>(entity, out var component))
            {
                var node = new CircuitNodeControl((entity, component), Canvas);

                node.OnDeleteRequested += (uid) =>
                    OnDeleteRequested?.Invoke(uid);

                Canvas.AddNode(node);
            }

        if (_sharedCircuit.GetChargeLevelFromSlot(Owner, out var charge))
            CircuitHud.SetPercent(charge.Value * 100);
    }

}
